adding cars
mirt735/yardman pull request #1
Opened 2022-12-04 21:37 UTC by andrew-larkin

2022-12-05 17:38 UTC, mirt735 requested changes

2022-12-05 17:38 UTC, mirt735 commented on src/main/java/solvo/yardman/models/CarType.java
> +    @OneToMany(mappedBy = "catType")
опечатка carType

2022-12-05 17:38 UTC, mirt735 commented on src/main/java/solvo/yardman/models/CarType.java
> +    @Column(name = "type")
Масло маслянное, хотя бы kind и пока не  очень понятно какие значения там будут

2022-12-05 17:38 UTC, mirt735 commented on src/main/java/solvo/yardman/models/CarType.java
> +    private Double capacity;
переименовать в "Грузоподъёмность"

2022-12-05 17:38 UTC, mirt735 commented on src/main/java/solvo/yardman/models/CarType.java
> +public class CarType {
Можно предзаполнить значениями отсюда https://apic.ru/proekti_apik/logistics/information/harakteristiki_gruzavto/

2022-12-05 17:38 UTC, mirt735 commented on src/main/java/solvo/yardman/models/CarType.java
> +    @OneToMany(mappedBy = "catType")
Еще раз подумать о необходимости двусторонней связи

2022-12-05 17:38 UTC, mirt735 commented on src/main/java/solvo/yardman/models/Car.java
> +    @Column(name = "last_driver_id")
подумать о необходимости поля

2022-12-05 17:38 UTC, mirt735 commented on src/main/java/solvo/yardman/models/Car.java
> +    @CreationTimestamp
вынести в отдельный абстрактный класс либо интерфейс либо найти нужные аннотации, которые это делают

2022-12-05 17:38 UTC, mirt735 commented on src/main/java/solvo/yardman/models/Car.java
> +    @Column(name = "modified", nullable = false, updatable = false)
вынести в отдельный абстрактный класс либо интерфейс либо найти нужные аннотации, которые это делают

2022-12-05 17:38 UTC, mirt735 commented on src/main/java/solvo/yardman/models/Car.java
> +    @Column(name = "carrier_id")
возможно стоит подумать о связи many-to-many с периодом действия

2022-12-06 21:02 UTC, andrew-larkin commented on src/main/java/solvo/yardman/models/Car.java
> +    @Column(name = "carrier_id")
тогда это будет не совсем many-to-many, но все равно довольно удобно: добавляем еще одну таблицу car_ownership с композитным ключом carrier_id + car_id и двумя столбцами: дата начала владения и дата окончания владения.

2022-12-07 17:15 UTC, closed without merging